travis:
  secure:
    BINSTAR_TOKEN: GOdZTrmeymrE9PhaF6SOLy3JHiuHE+NmDLl/MDkHS3/4hSpbpzStCS725SYBs3yd5a5JnyeovEmQvXFpHCQz0pE3qlUv9w27ggUfQO6SxpSK6N7s0ZvtuOsM7ojw3t7yzVYvAm/w6yzvKeQAAtuB6OaeoEGfpGC1t2dBWkjqTAN0EuB42BbqHAkVV/vD4oEM0TBbjDEtFe5aISsN3OekKxpwCNEVKHYWZCTs5Gyw8UjCCvTeSdJWB212OyQiM476WDhy+02KymBDTP8BicnJc/D/PDPCMeYlNdvy6AhjSL4DRxD/eJJBcy4AABCvkK3uvcDYBL0dT/o+79nHR/VoHYU4TP1XUcCKz3DCGHsxe8Zkok+aLLXTzzcF41nGwXbvsFLrrQr5jB8UJjiC7pKn2SOum5st6y1m1e4HNs+BSB+NfpbI4Cjz7MdU4BUq1Cc3zvuGqDmyx3O3CfTNWzRMU4p0WhaIc5I4zMKxsZrOfJ2d/vWEfgwkJfTFXV0wO0gO7YS8wEcH2dUW4kgDE4pfD/HDJKnOH+KxT6qf63Wb/qRI5KMcGhTcJwAJu0odb7gvcWI9yqaA3SCc7XgwQX9k2Qz8ljKdpvMCf/zhcWXhYvH1HZa4gadt3cboZOyegUnJ6M8ppVvigcr6coolX+l69FdJS3u/ENrm4Xdd1JcBAik=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
